### ISSUE TITLE
Is it specifically trained for the latex formula?

### ISSUE THREAD

**Issue by smclh** [NormXU/nougat-latex-ocr#1]
Hello, is this code specifically designed for training the latex formula? If it is text+formula, will it no longer work

**Comment by NormXU** [comment]
@smclh No, I think it should work. 

You can utilize the codes to fine-tune for various image-to-text tasks. The text associated with each image does not have to be in LaTeX code format; any text format will be fine. However, it may be necessary to customize the dataset to align with the specific textual content you intend to train for. Like the code [here](https://github.com/NormXU/nougat-latex-ocr/blob/main/mydatasets/donut_dataset.py#L79).

Besides, since the codes are to fine-tune from the pre-trained nougat models, if your target text format is part of nougat-pretraining data, to recover the markdown format of arxiv paper, I believe the fine-tuning will be quite effective.
